[package]
name = "dense-window-lib"
version = "0.1.0"
authors = ["Jiangqiu Shen <jshen2@mtu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
